### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by yonigold1** [kuestess/homebridge-platform-insteonlocal#124]
Is there a way to improve the delay when switching on a light to when it actually turns on? i find that when turning off my lights it's a far less delay versus turning on a light which takes longer

**Comment by kuestess** [comment]
@yonigold1 Haven't seen this issue in my setup - are you experiencing latency on the hub pro directly or via the serial over net connection (#122)?  There is a little extra delay added to 'on' commands because of the way the Home app works and the need to de-bounce on commands, although its on the order of milliseconds.  Most of the time latency is caused by a lot of Insteon traffic - do you have other services connected to your Hub?

**Comment by yonigold1** [comment]
So i found that when i would control my lighting from my hub pro homebridge setup it would delay like crazy but now that I use the pi the delay is much less on turning it off but the delay when turning it on is still there and its about a few seconds before something actually happens

**Comment by kuestess** [comment]
@yonigold1 Seems like its probably something specific to your setup.  Can you run homebridge in debug mode `homebridge -D` and post the log capturing the on/off actions?

**Comment by yonigold1** [comment]
so i managed to fix it up a bit by resetting everything on the pi and now it's running better :)
