### ISSUE TITLE
Using The HubPro Model 2243 (Beta) - Clarification 

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#180]
@kuestess I have a used 2243 coming with the idea of installing HomeBridge on it based on what you have in the docs here. I have done some googling and I cannot get one thing clear on this.

When you install this the Hub is no longer an InsteonHub that will respond to the Insteon IOS application, but a system running Linux and a connection to the onboard Insteon modem that can speak to the Insteon devices. Does this setup REPLACE having a my 2245?

**Comment by kuestess** [comment]
@sahafeez You're spot on - its just a Linux machine with a serial connection to an Insteon modem.  You can either replace or run it alongside your 2245.  I previously ran my 2243 (until it died, now running a PLM) together with a 2245, but honestly the only reason I kept the 2245 online was because I was too lazy to redo some of my more involved scenes in the ui (it can get admittedly complex).  There's currently no way to automatically migrate links/scenes over to a new hub, so you'll need to do that manually in the ui.  This is certainly something that is possible, but I have not had time to implement.

**Comment by sahafeez** [comment]
@kuestess thanks. One bit of confusion - the 2245 and 2243 keep the DB of devices in whatever OS Insteon is running on the HW. In the 2245 there is some unknown embedded that run Insteon system+modem that speaks Insteon. In the 2243 there is a known SOC that I can replace with linux and speak over serial to the modem which can speak to the Insteon devices. The thing that I am missing is if the Insteon DB still exist at that point - the Insteon devices see the modem ID as their link target right?

So I am thinking of this as if was running an ISY that runs software and uses the PLM to speak - so in the case above the DB is only in your application correct?

I could just get a PLM and hook it to a RPi? The advantage of the 2243 is just having the single package?

**Comment by kuestess** [comment]
@sahafeez The Insteon database is stored in the Hub itself, and device databases are stored in each respective device which is why you'll have to re-link your devices and recreate scenes.  The plugin downloads the database as JSON from the hub and each device, but the on-device db is the only one used.  Theoretically you could re-upload the JSON database to a new hub, but this isn't currently implemented.  A PLM connected to a RPi would work just as well.  Advantage of the 2243 as you state is a single package, and for many that were early adopters, turned an otherwise useless 2243 (because of crap software and little support) into a functioning Homekit hub.

**Comment by sahafeez** [comment]
@kuestess the thing that I am confused about is the DB stored on the hub - so do I need a hub running Insteon software if I have a 2243 that I installed the Linux kit on with Homebridge talking to the model. The Linux install replaces Insteon software as you are now booting from the flash card. So no Insteon sw running anywhere - just a modem that can be talked to, so it is like having an UD ISY994i + 2413S.

**Comment by kuestess** [comment]
@sahafeez Yep, like an ISY.  No need for Insteon software as the plugin can talk to them modem, read/write the db, etc.  No requirement for another Insteon hub on the Insteon network either.
