### ISSUE TITLE
lamp, switch, lightbulb, dimmer ? What are the differences?

### ISSUE THREAD

**Issue by ctgreybeard** [kuestess/homebridge-platform-insteonlocal#62]
What do the different appliance types do? I think I see that they drive what the icons are but is there anything else? And, if I chose incorrectly how do I  icon to update in Home? If I change it in config.json that doesn't seem to update Home.

**Comment by kuestess** [comment]
@ctgreybeard The main difference is that lightbulb/dimmer are dimmable devices, while the switch is on/off only.  From a practical standpoint, there's no difference in lightbulb and dimmer - they both implement the same Homekit device type and (as you note) have the same icon.  The icon should update if you switch it in your config (between switch and lightbulb/dimmer).  Alternately, you can go to settings for the individual device in Home, tap on the icon and change it there.

**Comment by ctgreybeard** [comment]
@kuestess Thanks for the reply. I'm trying to diagnose a problem I am having and I thought the device type might be it but I guess not. The problem I have is that I have at least one light (wall dimmer) that I can control using my own script calling home-controller but it will not control under homebridge. It DOES get correct status when polling though and changes state to agree with the actual state. I also see events logged when I control it manually at the switch. I just went around and tested a few devices and some control and others do not.

Here's my config. For every device I have the other (2413U) controller listed. Two devices I cannot control are Main Bath and DR Light, two I can control are LR Lamp and LR Pole. Could it be that more that one controller listed is causing a problem? Listing the other controller doesn't do what I hoped it did so I'll try removing those.

[config.json.zip](https://github.com/kuestess/homebridge-platform-insteonlocal/files/2938055/config.json.zip)

**Comment by ctgreybeard** [comment]
Well, removing that controller from the list didn't seem to do anything.

**Comment by kuestess** [comment]
@ctgreybeard The controllers features is intended to be devices rather than a PLM/Hub so it likely wont work as you’re thinking.  What you describe sounds like an issue with Insteon traffic - response can be slow to non-existent when there is a lot of Insteon traffic.  If you run in debug mode (`homebridge -D`) you’ll see all of the traffic coming through, and not just the traffic that the plugin responds to.  Having devices responding to multiple hubs will essentially double traffic.  Try running in debug mode and see if it works at a time when there’s not a lot of traffic (maybe do a config with only that device too) and see if that works.

**Comment by ctgreybeard** [comment]
It is absolutely not traffic. I say this because I have only a few devices defined and I was testing in the afternoon when there was nothing going on. I will run in debug and see what I can tell from that. I find it interesting that the polling updates succeed every time but the control commands do not ever succeed. And yet there are some devices that do work fine.

**Comment by ctgreybeard** [comment]
@kuestess The `-D` debug didn't really change much in the output so I used the DEBUG env variable. After letting the initial statuses update (it ends with `Entryway`) I tried controlling the `LR Lamp` which does control the light correctly. I then tried `DR Main` which, in the log, looks to be exactly the same but does nothing at all to the light itself. 

[homebridge.20190307-151103.log.zip](https://github.com/kuestess/homebridge-platform-insteonlocal/files/2942053/homebridge.20190307-151103.log.zip)

Can you look at this and see if you agree? If so I will take this over to the home-controller issue queue. When I use my own script to control `DR Main` it works correctly.

And, as an aside, can you tell me the basic steps to set up homebridge, insteonlocal and home-controller to do development/debug? I currently have homebridge and this plugin installed as --global.  If I need to dig into this I'll need a local environment to be able to make changes. I'm new at nodejs but not development.

**Comment by kuestess** [comment]
@ctgreybeard Is this perhaps an older dimmer?  Agree looking through the log that it is doing the same thing with an apparently different result ;-).  Looks like `home-controller` converts the 'set to level 100' command from the plugin (I use this rather than 'on' for very convoluted reasons) to Insteon command 0x21, which is an addition to the original command set.  Maybe try sending a direct command through your script with command1 = 21 and command2 = FF (100%) and see if the dimmer responds.  I've got a script that I can share later, but not at my main machine now.

I'm by no means a professional developer, but here's what works for me.  You can either pull down the repos that you're interested in or fork them and pull.  Change into the directory on your local machine and run `npm -g install` which should symlink that to your global `node_modules` directory.  I've moved to VSCode, which has dead simple debugging for nodejs.  I use `nodemon` with a setup similar to this: [https://github.com/Microsoft/vscode-recipes/tree/master/nodemon](https://github.com/Microsoft/vscode-recipes/tree/master/nodemon)

**Comment by ctgreybeard** [comment]
@kuestess Yes, this one happens to be an older dimmer but others are newer that don't respond also. I'll try what you suggest in my script.

**Comment by ctgreybeard** [comment]
I have attached the logs and some scripts from my tests. I think the difference is that this script generates an code `11` for command1 as opposed to the `21` that yours generates. My script controls the lights fine for all of my devices that I have tested.

I would question your use of `21` as it is a newer addition (20060420) and appears to bypass any ramp-level settings in the device.

Here are the scripts that I used for testing and the logs. The first line of each log shows the arguments that I used.

[ctldevice.zip](https://github.com/kuestess/homebridge-platform-insteonlocal/files/2946833/ctldevice.zip)

**Comment by kuestess** [comment]
@ctgreybeard The choice to use 0x21 was made by `home-controller`.  Not sure why they chose that - personally, I would have used 0x11.  Should be straightforward to implement using 0x11 instead.  Let me give it a shot.

**Comment by ctgreybeard** [comment]
Are you using Light.turnOn or Light.turnOnFast? I am using Light.turnOn which generates the `11`. I haven't tried the turnOnFast.

**Comment by ctgreybeard** [comment]
@kuestess I see what's happening now. The home-controller function `Light.level` uses the command1 `21` while `Light.turnOn` generates a command1 of `11` ... and I see that you use `Light.level` for the control.

Would it be possible to make using `Light.turnOn` a device option? With the corresponding `Light.turnOff` also? `Light.turnOn` will accept a level set and that does work with my devices. It has the added benefit (IMHO) of respecting the device's ramp rate that might be set.

**Comment by kuestess** [comment]
@ctgreybeard Reworked to use 0x11 rather than 0x21.  Try the update and let me know how that works for you.

**Comment by ctgreybeard** [comment]
@kuestess That works well! And because there aren't the timeouts from before it's pretty snappy!

**Comment by kuestess** [comment]
Fixed with 0.3.16-6.
