### ISSUE TITLE
Door Sensor Support?

### ISSUE THREAD

**Issue by THX723** [kuestess/homebridge-platform-insteonlocal#73]
Hi,
Are door open/close sensors currently supported?
If not, let me know how I might be able to help. Insteon makes 2 types. I've got the stick/hidden type (2845-222). Thanks.

**Comment by kuestess** [comment]
@THX723 Yes, you can specify 'doorsensor' , 'windowsensor', or 'contactsensor' in your config.  I don't have any so haven't tested thoroughly but let me know if you run into issues.  Looking at the readme, I seem to have forgotten to add so I'll update that as well.

**Comment by THX723** [comment]
@kuestess Super sweet! I'll give it a go tonight and report back.

**Comment by THX723** [comment]
@kuestess Okay I was able to remotely reconfigure my HB and the doorsensor appears to be responding in HomeKit. Nice. However the sensor state looked to be reversed. 

Just for kicks, I tried adding 'invert_sensor = true' parameter similar to iolinc/garagedoor. That did nothing as I don't think the code is there yet.

**Comment by kuestess** [comment]
@THX273 Since the door sensors are battery operated, they go to sleep most of the time and only wake up to broadcast an event. Because of this, it’s not possible to poll the status on initializing the device so it just gets a zero value which is open. It does broadcast state on an event, so it may take a few open/close cycles before it shows the proper state (and it should stay synced after that).  Let me know if you have opened/closed and it is still showing the incorrect state.

**Comment by THX723** [comment]
@kuestess Thanks for the extra details. Very helpful and maybe should also be included in the readme.
I'll report back after I have hands-on time later tonight.

**Comment by THX723** [comment]
@kuestess Success. Worked as described. Thanks again.
